spring:
  profiles:
    active:
    - dev

---
server:
  port: 8002
 
mybatis:
  mapper-locations: classpath:mapper/*.xml
spring:
  profiles: dev #开发环境
  application:
    name: micro-service-cloud-config-provider-server #开发环境
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/cloud01
eureka:
  client:
    service-url: 
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7005.com:7005/eureka
  instance:
    prefer-ip-address: true
    instance-id: micro-service-cloud-dept-8002
info: 
  app:
    name: zouqi-micro-service
  company:
    name: www.zouqi.cn
  build:
    artifactId: $project.artifactId$
    version: $project.version$     
    
---
server:
  port: 80001
 
mybatis:
  mapper-locations: classpath:mapper/*.xml
spring:
  profiles: test #开发环境
  application:
    name: micro-service-cloud-config-provider-server #开发环境
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/cloud01
eureka:
  client:
    service-url: 
      defaultZone: http://eureka7001.com:70001/eureka,http://eureka7002.com:70002/eureka,http://eureka7005.com:70005/eureka
  instance:
    prefer-ip-address: true
    instance-id: micro-service-cloud-dept-80001
info: 
  app:
    name: zouqi-micro-service
  company:
    name: www.zouqi.cn
  build:
    artifactId: $project.artifactId$
    version: $project.version$   
    
#注意保存为utf-8         
      